name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been marked as stale since it has had no activity within 30 days, and will be closed after 14 more days. Any activity on the issue will cause it to stay open."
          close-issue-message: "This issue has been closed due to a lack of activity. Please create a new issue if you feel like yours was not addressed."
          stale-pr-message: "This pull request has been marked as stale since it has had no activity within 30 days, and will be closed after 14 more days. Any activity on the pull request will cause it to stay open."
          close-pr-message: "This pull request has been closed due to a lack of activity. Please create a new pull request if you still want to contribute to this project."
          stale-issue-label: "s: stale"
          exempt-issue-labels: "s: WIP,s: in review"
          stale-pr-label: "s: stale"
          exempt-pr-labels: "s: WIP,s: in review"
          days-before-stale: 90
          days-before-close: 14
